### ISSUE TITLE
Use Video Labeler instead of Ground Truth Labeler

### ISSUE THREAD

**Issue by rickymedrano** [mathworks-robotics/deep-learning-for-object-detection-yolov2#2]
In the dataPreProcessing.mlx script, it uses the groundTruthLabeler app. The issue is that this app is apart of the Automated Driving Toolbax app, which I don't have. Could you update the script so it uses the Video Labeler instead? This would be better as that is apart of the Computer Vision Toolbox. The second reason you should update the script is because your code on [File Exchange](https://www.mathworks.com/matlabcentral/fileexchange/73954-deep-learning-for-object-detection?s_eid=PSM_15028) doesn't show Automated Driving Toolbox as a requirement under "Requires" so it's misleading.

**Comment by connelld92** [comment]
Hi Ricky, Thanks for your comment, I have updated the description of File Exchange to include the Automated Driving Toolbox. That being said the same code should work with the video labeler, I am working on an update with the files that I will push soon. If you use the video labeler, when you output the groundTruth data object to the workspace it should be in the same format as we have used in the code so there should be no problem using either app.

Thanks,
Connell
